<?php
/** Static administrator/consequential boundary checks for R46.9. */
declare(strict_types=1);
$root=dirname(__DIR__);$admin=file_get_contents($root.'/includes/Local_Retention_Admin.php');$service=file_get_contents($root.'/includes/Local_Retention_Service.php');$plugin=file_get_contents($root.'/includes/Plugin.php');$worker=file_get_contents($root.'/includes/PeerTube_Task_Worker.php');$launcher=file_get_contents($root.'/includes/PeerTube_Task_Worker_Launcher.php');$queue=file_get_contents($root.'/includes/Queue.php');
$f=0;$a=function(bool $v,string $m)use(&$f){if(!$v){fwrite(STDERR,"FAIL: $m\n");$f++;}};
$a(is_string($admin)&&str_contains($admin,"current_user_can('manage_options')")&&str_contains($admin,'check_admin_referer'),'Retention admin must require capability and nonce.');
$a(1===substr_count((string)$admin, "\$_GET['awvp_retention_notice']")&&str_contains((string)$admin,'phpcs:disable WordPress.Security.NonceVerification.Recommended -- Read-only redirect notice; it cannot mutate state.'),'Read-only retention redirect notice must be read exactly once under the reviewed nonce-verification suppression.');
$retention_admin_normalized=preg_replace('/\s+/','',(string)$admin)??'';
$a(str_contains($retention_admin_normalized,"sanitize_key(sanitize_text_field(wp_unslash(\$_GET['awvp_retention_notice']??'')))"),'Read-only retention redirect notice must be unslashed and sanitized at the superglobal read boundary.');
foreach(array('wp_delete_file','Storage::remove_tree','unlink(','wp_delete_attachment','wp_delete_post') as $needle)$a(!str_contains((string)$admin,$needle),"Admin request acquired inline destructive authority: $needle");
$a(str_contains((string)$service,"public const TASK_TYPE='peertube_local_retention_cleanup'")&&str_contains((string)$service,'$this->tasks->enqueue'),'Cleanup must be a durable queued task.');
$a(str_contains((string)$admin,'Local_Retention_Policy::MODE_DELETE_ALL ===')&&!str_contains((string)$admin,"if('removed'===\$source||'complete'===\$cleanup)"),'Completed managed-only cleanup must remain administratively reconfigurable; only irreversible full cleanup is frozen.');
$a(str_contains((string)$admin,'ACTION_ARCHIVE_POLICY')&&str_contains((string)$admin,'archive_policy_action')&&str_contains((string)$admin,'confirm_archive_change'),'Retention UI lacks the site-wide archive-of-record transition boundary.');
$a(!str_contains((string)$admin,'name="master_authority"')&&!str_contains((string)$admin,'name="confirm_cleanup"'),'Retention UI still asks for repetitive per-video master/cleanup confirmation.');
$a(str_contains((string)$admin,'WordPress is the archive of record for original videos.')&&str_contains((string)$admin,'WordPress is not the archive of record for original videos.'),'Retention UI does not present the two site-wide archive-of-record choices.');
$a(str_contains((string)$admin,'if (! $wordpress_archive)')&&str_contains((string)$admin,'value="delete_all"'),'Original-source deletion option is not gated by site archive-of-record policy.');
$a(str_contains((string)$service,'configure_for_site_policy')&&substr_count((string)$service,'source_deletion_allowed()')>=3,'Retention service does not re-check site source-deletion authority through configure/schedule/worker boundaries.');

$a(str_contains((string)$admin,'ACTION_DEFAULT_POLICY')&&str_contains((string)$admin,'ACTION_BULK_APPLY')&&str_contains((string)$admin,'AWVP Default Policy')&&str_contains((string)$admin,'Apply AWVP Default Policy to selected videos'),'Retention UI lacks the site-wide default-policy/bulk-apply workflow.');
$a(str_contains((string)$admin,'awvp-retention-filter')&&str_contains((string)$admin,'awvp-retention-select-visible')&&str_contains((string)$admin,'video_ids[]'),'Retention UI lacks searchable/filterable bulk video selection and select-all-visible controls.');
$a(str_contains((string)$admin,'Video serving choice and source retention policies are separate items.')&&str_contains((string)$admin,'Check this to enable saving WordPress as NOT your Archive of Record.')&&str_contains((string)$admin,'Media retention policies are set by your chosen backend servers'),'Retention explanatory/archive-of-record copy does not match the reviewed live-test wording.');
$a(str_contains((string)$plugin,"new Local_Retention_Default_Policy_Store()")&&str_contains((string)$plugin,"Local_Retention_Admin::ACTION_DEFAULT_POLICY")&&str_contains((string)$plugin,"Local_Retention_Admin::ACTION_BULK_APPLY"),'Production default-policy/bulk retention wiring incomplete.');
$a(str_contains((string)$worker,"'peertube_local_retention_cleanup'")&&str_contains((string)$launcher,"'peertube_local_retention_cleanup'"),'Detached worker/launcher do not own retention cleanup.');
$onceStart=strpos((string)$worker,'private const ONCE_TASK_TYPES');$drainStart=strpos((string)$worker,'private const DRAIN_TASK_TYPES');$a(false!==$onceStart&&false!==$drainStart&&!str_contains(substr((string)$worker,$onceStart,$drainStart-$onceStart),'peertube_local_retention_cleanup'),'Retention cleanup must not broaden qualified --once diagnostics.');
$a(str_contains((string)$queue,'attachment_local_processing_blocked($attachment_id)'),'Normal local queue is not fenced against running/completed destructive retention.');
$a(str_contains((string)$plugin,"admin_post_' . Local_Retention_Admin::ACTION_CONFIGURE")&&str_contains((string)$plugin,"admin_post_' . Local_Retention_Admin::ACTION_ARCHIVE_POLICY")&&str_contains((string)$plugin,"new Archive_Of_Record_Policy_Store()")&&str_contains((string)$plugin,"array(\$local_retention_service, 'advance_claimed')"),'Production retention/archive-policy wiring incomplete.');
if($f>0)exit(1);echo "R46.9 retention administrator/boundary tests passed.\n";
