<?php
/** Focused remote-publication health email delivery tests. */
declare(strict_types=1);
namespace ArgentVideo {
final class Remote_Health_Notification_Policy_Store{public const OFF='off';public const DELAYED='delayed';public const IMMEDIATE='immediate';public array $policy=array('administrator'=>'immediate','publishing_user'=>'immediate','origin_author'=>'immediate');public function get():array{return $this->policy;}public static function due(string $m,int $f,int $n):bool{return self::IMMEDIATE===$m||(self::DELAYED===$m&&$n-$f>=7200);}}
final class Remote_Health_Notification_State_Store{public array $assets=array();public array $backends=array();private static function e():array{return array('failure_since'=>0,'notified_roles'=>array(),'recovered_roles'=>array(),'updated_at'=>0);}public function asset(int $id):array{return $this->assets[$id]??self::e();}public function backend(string $id):array{return $this->backends[$id]??self::e();}public function mark_asset(int $id,int $f,array $r,int $n,bool $rec=false):bool{$x=$this->assets[$id]??self::e();if($x['failure_since']!==$f)$x=array('failure_since'=>$f,'notified_roles'=>array(),'recovered_roles'=>array(),'updated_at'=>$n);$k=$rec?'recovered_roles':'notified_roles';$x[$k]=array_values(array_unique(array_merge($x[$k],$r)));sort($x[$k]);$x['updated_at']=$n;$this->assets[$id]=$x;return true;}public function mark_backend(string $id,int $f,array $r,int $n,bool $rec=false):bool{$x=$this->backends[$id]??self::e();if($x['failure_since']!==$f)$x=array('failure_since'=>$f,'notified_roles'=>array(),'recovered_roles'=>array(),'updated_at'=>$n);$k=$rec?'recovered_roles':'notified_roles';$x[$k]=array_values(array_unique(array_merge($x[$k],$r)));sort($x[$k]);$x['updated_at']=$n;$this->backends[$id]=$x;return true;}public function clear_asset(int $id):bool{unset($this->assets[$id]);return true;}public function clear_backend(string $id):bool{unset($this->backends[$id]);return true;}}
final class Video_Serving_Service{public array $candidate=array('backend_id'=>'local');public function serving_candidate(int $id):array{return $this->candidate;}}
final class PeerTube_Event_Repository{public array $events=array();public function record(int $video_id,int $step,string $code,string $severity,string $message,int $now,int $task=0,string $op='',int $asset=0,string $backend='',int $http=0,string $auto='',string $operator='',array $ctx=array()):bool{$this->events[]=compact('video_id','step','code','severity','message','now','asset','backend','ctx');return true;}}
final class PeerTube_Publication_Execution{public static function sanitize(mixed $v):array{return is_array($v)?$v:array();}}
final class Video_Meta{public const PEERTUBE_PUBLICATION_EXECUTION='_exec';public const ORIGIN_POST_ID='_origin';public static function sanitize_positive_id(mixed $v):int{return is_numeric($v)&&((int)$v)>0?(int)$v:0;}}
final class Backend_Registry{public const LOCAL_ID='local';}
final class Backend_Identity{public static function sanitize(mixed $v):string{return is_string($v)?$v:'';}}
final class Serving_Viability{public const HEALTHY='healthy';public const PROCESSING='processing';}
}
namespace {
$GLOBALS['awvp_notify_mail']=array();$GLOBALS['awvp_notify_meta']=array(77=>array('_exec'=>array('operation_id'=>'upload_aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'),'_origin'=>88));$GLOBALS['awvp_notify_users']=array(5=>(object)array('user_email'=>'admin@example.test'),6=>(object)array('user_email'=>'author@example.test'));
function get_option(string $k,mixed $d=false):mixed{return 'admin_email'===$k?'admin@example.test':$d;}function is_email(string $e):string|false{return filter_var($e,FILTER_VALIDATE_EMAIL)?$e:false;}function wp_mail(string|array $to,string $subject,string $message,string|array $headers='',array $attachments=array()):bool{$GLOBALS['awvp_notify_mail'][]=array('to'=>$to,'subject'=>$subject,'message'=>$message);return true;}function get_bloginfo(string $k=''):string{return 'AWVP Test';}function get_the_title(int $id):string{return 77===$id?'Test Video':'';}function get_post_meta(int $id,string $key,bool $single=false):mixed{return $GLOBALS['awvp_notify_meta'][$id][$key]??'';}function get_post(int $id):mixed{return 88===$id?(object)array('post_author'=>6):null;}function get_userdata(int $id):mixed{return $GLOBALS['awvp_notify_users'][$id]??false;}
require_once dirname(__DIR__).'/includes/Remote_Health_Notification_Service.php';
use ArgentVideo\Remote_Health_Notification_Policy_Store as Policy;use ArgentVideo\Remote_Health_Notification_State_Store as State;use ArgentVideo\Video_Serving_Service as Serving;use ArgentVideo\PeerTube_Event_Repository as Events;use ArgentVideo\Remote_Health_Notification_Service as Service;
$a=static function(bool $ok,string $m):void{if(!$ok){fwrite(STDERR,"FAIL: $m\n");exit(1);}};$policy=new Policy();$state=new State();$serving=new Serving();$events=new Events();$ops=static fn(string $id):?array=>array('created_by'=>5);$svc=new Service($policy,$state,$serving,$ops,$events);
$asset=array('id'=>9,'video_post_id'=>77,'backend_id'=>'pt1');$health=array('status'=>'missing','failure_since'=>'1970-01-01 00:16:40','message'=>'Gone','http_status'=>404);
$svc->publication_observed($asset,$health,1000,false);$a(2===count($GLOBALS['awvp_notify_mail']),'Deduplicated immediate alert should send once to shared admin/publisher email and once to author.');$r=$state->asset(9);$a(array('administrator','origin_author','publishing_user')===$r['notified_roles'],'Successful alert did not mark all recipient roles.');
$svc->publication_observed($asset,$health,1100,false);$a(2===count($GLOBALS['awvp_notify_mail']),'Repeated failed probe resent same incident alert.');
$svc->publication_observed($asset,array('status'=>'healthy','failure_since'=>null),1200,false);$a(4===count($GLOBALS['awvp_notify_mail']),'Recovery did not notify prior recipients once.');$a(0===$state->asset(9)['failure_since'],'Recovery did not clear completed incident journal.');
$GLOBALS['awvp_notify_mail']=array();$svc->publication_observed($asset,$health,2000,true);$a(0===count($GLOBALS['awvp_notify_mail']),'Backend-wide outage must suppress per-video email fanout.');$incident=array('failure_since'=>2000,'message'=>'Server down','http_status'=>503);$svc->backend_observed('pt1',null,$incident,2000);$a(1===count($GLOBALS['awvp_notify_mail']),'Backend outage should send one administrator alert.');$svc->backend_observed('pt1',$incident,null,2100);$a(2===count($GLOBALS['awvp_notify_mail']),'Backend recovery should send one administrator recovery email.');
fwrite(STDOUT,"Remote health notification service tests passed.\n");
}
