<?php
/** Dependency-free R46.6 cutover + frontend resolver tests. */
declare(strict_types=1);
$GLOBALS['r466_meta']=array();$GLOBALS['r466_posts']=array();$GLOBALS['r466_meta_cache']=array();$GLOBALS['r466_post_cache']=array();$GLOBALS['r466_cache_deletes']=array();
function absint(mixed $v):int{return abs((int)$v);} function sanitize_key(mixed $v):string{return strtolower((string)$v);} function sanitize_text_field(mixed $v):string{return trim(strip_tags((string)$v));} function wp_json_encode(mixed $v,int $flags=0):string|false{return json_encode($v,$flags);} function wp_parse_url(string $v):array|false{return parse_url($v);}
function get_post(int $id):object|false{return $GLOBALS['r466_post_cache'][$id]??$GLOBALS['r466_posts'][$id]??false;} function get_post_meta(int $id,string $k,bool $single=false):mixed{$source=array_key_exists($id,$GLOBALS['r466_meta_cache'])?$GLOBALS['r466_meta_cache']:$GLOBALS['r466_meta'];$v=$source[$id][$k]??($single?'':array());return $single?$v:array($v);} function metadata_exists(string $type,int $id,string $k):bool{$source=array_key_exists($id,$GLOBALS['r466_meta_cache'])?$GLOBALS['r466_meta_cache']:$GLOBALS['r466_meta'];return 'post'===$type&&array_key_exists($k,$source[$id]??array());} function update_post_meta(int $id,string $k,mixed $v):int|bool{$GLOBALS['r466_meta'][$id][$k]=$v;return 1;} function delete_post_meta(int $id,string $k):bool{unset($GLOBALS['r466_meta'][$id][$k]);unset($GLOBALS['r466_meta_cache'][$id][$k]);return true;} function wp_cache_delete(mixed $key,string $group=''):bool{$GLOBALS['r466_cache_deletes'][]=$group.':'.(string)$key;if('post_meta'===$group)unset($GLOBALS['r466_meta_cache'][(int)$key]);if('posts'===$group)unset($GLOBALS['r466_post_cache'][(int)$key]);return true;}
require_once dirname(__DIR__).'/includes/Serving_Viability.php';require_once dirname(__DIR__).'/includes/Backend_Identity.php';require_once dirname(__DIR__).'/includes/Backend_Registry.php';require_once dirname(__DIR__).'/includes/PeerTube_Connection_Input.php';require_once dirname(__DIR__).'/includes/PeerTube_Origin.php';require_once dirname(__DIR__).'/includes/Video_Destination.php';require_once dirname(__DIR__).'/includes/PeerTube_Publication_Plan.php';require_once dirname(__DIR__).'/includes/PeerTube_Publication_Lifecycle.php';require_once dirname(__DIR__).'/includes/PeerTube_Publication_Manifest.php';require_once dirname(__DIR__).'/includes/PeerTube_Publication_Execution.php';require_once dirname(__DIR__).'/includes/Video_Serving_Authority.php';require_once dirname(__DIR__).'/includes/PeerTube_Publication_Asset_Store.php';require_once dirname(__DIR__).'/includes/Video_Post_Type.php';require_once dirname(__DIR__).'/includes/Video_Meta.php';require_once dirname(__DIR__).'/includes/PeerTube_Serving_Cutover_Service.php';require_once dirname(__DIR__).'/includes/Video_Serving_Resolver.php';require_once dirname(__DIR__).'/includes/Video_Serving_Service.php';
use ArgentVideo\PeerTube_Publication_Plan as Plan;use ArgentVideo\PeerTube_Publication_Lifecycle as Lifecycle;use ArgentVideo\PeerTube_Publication_Manifest as Manifest;use ArgentVideo\PeerTube_Publication_Execution as Execution;use ArgentVideo\Video_Meta;use ArgentVideo\Video_Post_Type;use ArgentVideo\PeerTube_Publication_Asset_Store;use ArgentVideo\PeerTube_Serving_Cutover_Service as Cutover;use ArgentVideo\Video_Serving_Service;
final class R466Assets implements PeerTube_Publication_Asset_Store{public array $rows=array();public function find(int $id):?array{return $this->rows[$id]??null;}public function record_publication_observation(int $a,int $b,string $c,string $d,string $e,string $f,int $g):string{return 'present';}}
$a=static function(bool $ok,string $m):void{if(!$ok){fwrite(STDERR,"FAIL: $m\n");exit(1);}};
$plan=array('version'=>1,'backend_id'=>'pt-primary','channel_id'=>'41','title'=>'Reviewed title','description_markdown'=>'','tags'=>array(),'support'=>array('mode'=>'none','preset_id'=>'','markdown'=>''),'final_privacy_id'=>'1','licence_id'=>'','category_id'=>'','language'=>'','thumbnail_attachment_id'=>0,'download_enabled'=>true,'originally_published_at'=>'','comments_policy'=>'enabled','moderation'=>array('reviewed'=>true,'sensitive'=>false,'reason'=>'','violent'=>false,'sexually_explicit'=>false),'embed'=>array('restricted'=>false,'domains'=>array()),'review'=>array('title'=>true,'channel'=>true,'tags'=>true,'privacy'=>true,'moderation'=>true),'dispatch_policy'=>Plan::DISPATCH_SEND_NOW,'release_policy'=>Plan::RELEASE_WHEN_WORDPRESS_PUBLISHED,'anchor_post_id'=>10);$sha=Lifecycle::plan_sha256($plan);
$lifecycle=Lifecycle::sanitize(array('version'=>1,'generation'=>4,'backend_id'=>'pt-primary','anchor_post_id'=>10,'plan_sha256'=>$sha,'dispatch_policy'=>Plan::DISPATCH_SEND_NOW,'wordpress_status'=>'publish','upload_authorized'=>true,'reveal_authorized'=>true,'target_privacy_id'=>'1','task_pending'=>false,'updated_at'=>1000));$manifest=Manifest::sanitize(array('version'=>1,'backend_id'=>'pt-primary','channel_id'=>'41','anchor_post_id'=>10,'plan_sha256'=>$sha,'title'=>'Reviewed title','description_markdown'=>'','tags'=>array(),'support_markdown'=>'','final_privacy_id'=>'1','licence_id'=>'','category_id'=>'','language'=>'','thumbnail_attachment_id'=>0,'thumbnail_sha256'=>'','thumbnail_bytes'=>0,'thumbnail_mime'=>'','download_enabled'=>true,'originally_published_at'=>'','comments_policy'=>'enabled','moderation'=>array('reviewed'=>true,'sensitive'=>false,'reason'=>'','violent'=>false,'sexually_explicit'=>false)));$execution=Execution::create($manifest,1000);$execution=Execution::with_operation($execution,'upload_'.str_repeat('a',32),1010);$execution=Execution::with_remote($execution,55,'123e4567-e89b-42d3-a456-426614174000',1020);$execution=Execution::mark_applied($execution,$manifest,1030);
$GLOBALS['r466_posts'][77]=(object)array('ID'=>77,'post_type'=>Video_Post_Type::POST_TYPE,'post_status'=>'publish');$GLOBALS['r466_posts'][10]=(object)array('ID'=>10,'post_type'=>'post','post_status'=>'publish');$GLOBALS['r466_meta'][77]=array(Video_Meta::DESTINATION=>array('version'=>1,'backend_id'=>'pt-primary','channel_id'=>'41'),Video_Meta::PEERTUBE_PUBLICATION_PLAN=>$plan,Video_Meta::PEERTUBE_PUBLICATION_LIFECYCLE=>$lifecycle,Video_Meta::PEERTUBE_PUBLICATION_EXECUTION=>$execution);
$assets=new R466Assets();$assets->rows[55]=array('id'=>55,'video_post_id'=>77,'backend_id'=>'pt-primary','channel_id'=>'41','remote_id'=>'123e4567-e89b-42d3-a456-426614174000','role'=>'secondary','state'=>'ready','desired_privacy'=>'public','actual_privacy'=>'public','remote_processing_state'=>'1:published','embed_url'=>'https://video.example.org/videos/embed/5wwQY8261uRv7aPsVWhEiY','last_verified_at'=>'2026-09-07 13:00:00');
$cut=new Cutover($assets);$a(Cutover::APPLIED===$cut->reconcile(77,1100),'Verified public asset did not cut over.');$a(metadata_exists('post',77,Video_Meta::SERVING_AUTHORITY),'Cutover did not persist serving authority.');$a(Cutover::PRESENT===$cut->reconcile(77,1100),'Exact cutover replay was not idempotent.');$serve=new Video_Serving_Service($assets);$a('https://video.example.org/videos/embed/5wwQY8261uRv7aPsVWhEiY'===$serve->peertube_embed_url(77),'Frontend resolver rejected verified PeerTube short embed ID authority.');
// New lifecycle generation must immediately force local fallback even before stale cutover metadata is deleted.
$new=$lifecycle;$new['generation']=5;$new['wordpress_status']='draft';$new['reveal_authorized']=false;$new['target_privacy_id']='3';$new['updated_at']=1200;$GLOBALS['r466_meta'][77][Video_Meta::PEERTUBE_PUBLICATION_LIFECYCLE]=$new;$GLOBALS['r466_posts'][10]->post_status='draft';$a(''===$serve->peertube_embed_url(77),'Stale serving authority survived WordPress lifecycle supersession.');
// Reproduce a long-lived worker that still has the old generation/post cached.
// Cutover must invalidate both caches before deciding whether remote serving is allowed.
$GLOBALS['r466_meta_cache'][77]=$GLOBALS['r466_meta'][77];$GLOBALS['r466_meta_cache'][77][Video_Meta::PEERTUBE_PUBLICATION_LIFECYCLE]=$lifecycle;$GLOBALS['r466_post_cache'][10]=(object)array('ID'=>10,'post_type'=>'post','post_status'=>'publish');
$a(Cutover::LOCAL===$cut->reconcile(77,1200),'Private/draft lifecycle did not clear remote serving authority after stale cache invalidation.');$a(!metadata_exists('post',77,Video_Meta::SERVING_AUTHORITY),'Stale serving authority remained after local reconciliation.');$a(in_array('post_meta:77',$GLOBALS['r466_cache_deletes'],true)&&in_array('posts:10',$GLOBALS['r466_cache_deletes'],true),'Serving cutover did not refresh lifecycle/anchor caches.');
// Restored publication with an uncertain remote row must remain local.
$GLOBALS['r466_meta'][77][Video_Meta::PEERTUBE_PUBLICATION_LIFECYCLE]=$lifecycle;$GLOBALS['r466_posts'][10]->post_status='publish';$assets->rows[55]['last_verified_at']='';$a(Cutover::REFUSED===$cut->reconcile(77,1300),'Unverified remote asset authorized cutover.');$a(''===$serve->peertube_embed_url(77),'Unverified remote asset resolved as serving authority.');
fwrite(STDOUT,"R46.6 serving cutover/resolver tests passed.\n");
